-- Run this script in your Supabase SQL Editor to insert 25 mock users
-- Note: This script inserts into auth.users (to satisfy foreign keys and auth) 
-- and then updates public.profiles (which are auto-generated by the trigger).

-- Enable pgcrypto for password hashing if not already enabled
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
DECLARE
  -- Generate 25 UUIDs
  u1 UUID := gen_random_uuid(); u2 UUID := gen_random_uuid(); u3 UUID := gen_random_uuid(); u4 UUID := gen_random_uuid(); u5 UUID := gen_random_uuid();
  u6 UUID := gen_random_uuid(); u7 UUID := gen_random_uuid(); u8 UUID := gen_random_uuid(); u9 UUID := gen_random_uuid(); u10 UUID := gen_random_uuid();
  u11 UUID := gen_random_uuid(); u12 UUID := gen_random_uuid(); u13 UUID := gen_random_uuid(); u14 UUID := gen_random_uuid(); u15 UUID := gen_random_uuid();
  u16 UUID := gen_random_uuid(); u17 UUID := gen_random_uuid(); u18 UUID := gen_random_uuid(); u19 UUID := gen_random_uuid(); u20 UUID := gen_random_uuid();
  u21 UUID := gen_random_uuid(); u22 UUID := gen_random_uuid(); u23 UUID := gen_random_uuid(); u24 UUID := gen_random_uuid(); u25 UUID := gen_random_uuid();
  default_pass TEXT := crypt('password123', gen_salt('bf'));
BEGIN

  -- 1. Insert into auth.users (This will trigger public.handle_new_user() and create empty profiles)
  INSERT INTO auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
  VALUES
  (u1, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user1@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Alex Chen"}', now(), now()),
  (u2, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user2@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Sarah Jenkins"}', now(), now()),
  (u3, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user3@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Mike Ross"}', now(), now()),
  (u4, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user4@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Elena Gilbert"}', now(), now()),
  (u5, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user5@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"David Kim"}', now(), now()),
  (u6, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user6@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Rachel Zane"}', now(), now()),
  (u7, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user7@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Harvey Specter"}', now(), now()),
  (u8, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user8@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Donna Paulsen"}', now(), now()),
  (u9, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user9@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Louis Litt"}', now(), now()),
  (u10, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user10@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Katrina Bennett"}', now(), now()),
  (u11, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user11@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Jessica Pearson"}', now(), now()),
  (u12, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user12@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Robert Zane"}', now(), now()),
  (u13, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user13@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Samantha Wheeler"}', now(), now()),
  (u14, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user14@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Alex Williams"}', now(), now()),
  (u15, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user15@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Brian Altman"}', now(), now()),
  (u16, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user16@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Sheila Sazs"}', now(), now()),
  (u17, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user17@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Gretchen Bodinski"}', now(), now()),
  (u18, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user18@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Jeff Malone"}', now(), now()),
  (u19, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user19@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Sean Cahill"}', now(), now()),
  (u20, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user20@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Daniel Hardman"}', now(), now()),
  (u21, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user21@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Stephen Huntley"}', now(), now()),
  (u22, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user22@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Charles Forstman"}', now(), now()),
  (u23, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user23@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Edward Darby"}', now(), now()),
  (u24, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user24@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Ava Hessington"}', now(), now()),
  (u25, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'user25@syncstudy.com', default_pass, now(), '{"provider":"email","providers":["email"]}', '{"full_name":"Cameron Dennis"}', now(), now());

  -- 2. Update the public.profiles table (which was auto-created by the trigger)
  -- Group 1: Computer Science, Sem 6, Python/Java, Night Owls (8 users)
  UPDATE public.profiles SET 
    college = 'Stanford University', branch = 'Computer Science', semester = 6, 
    subjects = '{"Data Structures", "Algorithms", "Machine Learning"}', exams = '{"GRE", "GATE"}', goals = 'Prepare for FAANG interviews', timings = 'night', learning_style = 'visual', language = 'English', verification_status = 'verified'
  WHERE id IN (u1, u2, u3, u4, u5, u6, u7, u8);

  -- Group 2: Mechanical Engineering, Sem 4, Thermodynamics/CAD, Early Birds (5 users)
  UPDATE public.profiles SET 
    college = 'MIT', branch = 'Mechanical Engineering', semester = 4, 
    subjects = '{"Thermodynamics", "AutoCAD", "Fluid Mechanics"}', exams = '{"GATE", "IES"}', goals = 'Complete semester projects', timings = 'morning', learning_style = 'practical', language = 'English', verification_status = 'verified'
  WHERE id IN (u9, u10, u11, u12, u13);

  -- Group 3: Computer Science, Sem 2, C/C++, Any time (5 users)
  UPDATE public.profiles SET 
    college = 'UC Berkeley', branch = 'Computer Science', semester = 2, 
    subjects = '{"Introduction to Programming", "Discrete Math"}', exams = '{"Midterms"}', goals = 'Pass finals with flying colors', timings = 'afternoon', learning_style = 'reading', language = 'English', verification_status = 'verified'
  WHERE id IN (u14, u15, u16, u17, u18);

  -- Group 4: Business/Marketing, Sem 4, Finance/Economics, Early Birds (4 users)
  UPDATE public.profiles SET 
    college = 'Harvard Business School', branch = 'Business Administration', semester = 4, 
    subjects = '{"Macroeconomics", "Corporate Finance", "Marketing"}', exams = '{"GMAT"}', goals = 'Case study preparations', timings = 'morning', learning_style = 'auditory', language = 'Spanish', verification_status = 'verified'
  WHERE id IN (u19, u20, u21, u22);

  -- Group 5: Outliers / Diverse subjects (3 users)
  UPDATE public.profiles SET 
    college = 'Oxford University', branch = 'Literature', semester = 8, 
    subjects = '{"Shakespeare", "Poetry"}', exams = '{"Thesis"}', goals = 'Write dissertation', timings = 'night', learning_style = 'reading', language = 'French', verification_status = 'verified'
  WHERE id = u23;

  UPDATE public.profiles SET 
    college = 'NYU', branch = 'Film Studies', semester = 3, 
    subjects = '{"Cinematography", "Screenwriting"}', exams = '{"Finals"}', goals = 'Complete short film', timings = 'afternoon', learning_style = 'visual', language = 'English', verification_status = 'verified'
  WHERE id = u24;

  UPDATE public.profiles SET 
    college = 'University of Tokyo', branch = 'Robotics', semester = 5, 
    subjects = '{"AI", "Mechatronics"}', exams = '{"JLPT"}', goals = 'Build a robot', timings = 'morning', learning_style = 'practical', language = 'Japanese', verification_status = 'verified'
  WHERE id = u25;

END $$;
